version: '2'

services:
  app:
    build: pgadmin
    restart: always
    environment:
      - PG_SERVERS
      - PG_SERVERS_PUBLIC_IPS
    volumes:
      - /usr/share/nginx/html
      - ${PGADMIN_CONFIG_PATH}:/usr/share/nginx/html/conf/external-config.inc.php:ro
  web:
    build: nginx
    restart: always
    depends_on:
      - app
    ports:
      - "${NGINX_HTTP_PORT}:80"
    volumes_from:
      - app:ro
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://servers.php"]
    #  interval: 1m30s
    #  timeout: 10s
    #  retries: 3
