version: '2'

services:
  app:
    build: pgadmin
    restart: always
    environment:
      - PG_SERVERS_DOCKER_IPS
      - PG_SERVERS_EXTERNAL_ADDRS
    volumes:
      - /usr/share/nginx/html
      - ./pgadmin/themes/default.dev:/usr/share/nginx/html/themes/default.dev
      - ./pgadmin/themes/default.prod:/usr/share/nginx/html/themes/default.prod
      - ./pgadmin/themes/default.test:/usr/share/nginx/html/themes/default.test
      - ${PGADMIN_CONFIG_PATH}:/usr/share/nginx/html/conf/external-config.inc.php:ro
  web:
    build: nginx
    restart: always
    depends_on:
      - app
    ports:
      - "${NGINX_HTTP_PORT}:80"
    volumes_from:
      - app:ro
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://servers.php"]
    #  interval: 1m30s
    #  timeout: 10s
    #  retries: 3
