version: '2'

services:
  app:
    build: pgadmin
    volumes:
      - /usr/share/nginx/html
  web:
    build: nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes_from:
      - app:ro
