version: '2'

services:
  app:
    build: pgadmin
    restart: always
    network_mode: host
    volumes:
      - /usr/share/nginx/html
      - ${PGADMIN_CONFIG_PATH}:/usr/share/nginx/html/conf/config.inc.php:ro
  web:
    build: nginx
    restart: always
    network_mode: host
    depends_on:
      - app
    ports:
      - "${NGINX_HTTP_PORT}:12380"
    volumes_from:
      - app:ro
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://servers.php"]
    #  interval: 1m30s
    #  timeout: 10s
    #  retries: 3
