version: '2'

services:
  web:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "80:80"
    volumes_from:
      - app:ro
  app:
    build: .
    volumes:
      - /usr/share/nginx/html

# @TODO Mount/copy config for nginx server with php-fpm
